server:
  port: 8888

spring:
  security:
    user:
      name: configUser
      password: configPassword
      roles: SYSTEM
  application:
    name: configservice
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LittleJ0hnny/config-repo.git

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'


