FROM openjdk:8u181-jdk

EXPOSE 8400

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install netcat

COPY img-service/build/libs/img-service-1.0-SNAPSHOT.jar img-service-1.0-SNAPSHOT.jar
COPY docker/bootstrap-img-server.sh bootstrap-img-server.sh

RUN chown 755 bootstrap-img-server.sh

CMD ["bash", "bootstrap-img-server.sh"]