FROM openjdk:8u181-jdk

EXPOSE 8400

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install netcat

COPY img-service/build/libs/img-service-1.0-SNAPSHOT.jar img-service-1.0-SNAPSHOT.jar
COPY docker/bootstrap3.sh bootstrap3.sh

RUN chown 755 bootstrap3.sh

CMD ["bash", "bootstrap3.sh"]