FROM openjdk:8u181-jdk

EXPOSE 8200

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install netcat

COPY auth/build/libs/auth-1.0-SNAPSHOT.jar auth-1.0-SNAPSHOT.jar
COPY docker/bootstrap-auth.sh bootstrap-auth.sh

RUN chown 755 bootstrap-auth.sh

CMD ["bash", "bootstrap-auth.sh"]